/*
* Generated by GObjectCreator at 2010-08-21T12:10:37.510952.
* Please edit user code sections only!
*
* For more info on GObjectCreator see: http://www.bollmeier.de/GObjectCreator
*/

#include "audio_error.h"

GQuark audio_error_quark() {

    return g_quark_from_static_string("audio_error_quark");
    
}
