/*
* Generated by GObjectCreator at 2010-08-21T12:10:37.507263.
* Please edit user code sections only!
*
* For more info on GObjectCreator see: http://www.bollmeier.de/GObjectCreator
*/

#ifndef AUDIO_ERROR_H
#define AUDIO_ERROR_H

#include "glib-object.h"

G_BEGIN_DECLS

#define AUDIO_ERROR audio_error_quark()
GQuark audio_error_quark();

enum AudioError {
    AUDIO_ERROR_INVALID_STATUS = 1,
    AUDIO_ERROR_URI_NOT_FOUND,
    AUDIO_ERROR_UNKNOWN_FORMAT
};

G_END_DECLS

#endif
