/*
* Generated by GObjectCreator at 2010-08-21T12:10:37.518620.
* Please edit user code sections only!
*
* For more info on GObjectCreator see: http://www.bollmeier.de/GObjectCreator
*/

#ifndef AUDIO_FORMAT_H
#define AUDIO_FORMAT_H

#include "glib-object.h"

G_BEGIN_DECLS

typedef enum _AudioFormat {
    AUDIO_FORMAT_MP3,
    AUDIO_FORMAT_OGG_VORBIS
} AudioFormat;

GType audio_format_get_type();

#define AUDIO_TYPE_FORMAT audio_format_get_type()

G_END_DECLS

#endif
